import { createAudioPlayer, type AudioPlayer } from 'expo-audio';

/**
 * FEATURES.md §8 — what a timer says without being looked at.
 *
 * A hold usually means the phone is on the floor or propped against a wall
 * rather than in your hand, so a haptic alone can go unfelt. The sound is what
 * actually reaches you; `lib/haptics.ts` fires alongside for the case where it
 * does not.
 *
 * **Three tones, because a countdown has three things to say.** Time is nearly
 * up; the effort is over; the rest is over. The count is a neutral note and the
 * two endings resolve away from it in opposite directions — down to stop, up to
 * go — so telling them apart is hearing a direction rather than remembering a
 * pattern. That matters most in §8.2's cycle, which runs hands-free with the
 * phone on the floor, where one tone would have to mean both *stop* and *go*.
 *
 * The endings are long where the count is short. `lib/countdown.ts` starts them
 * on the final second, so the tone runs out as the figure does and nothing at
 * all plays at zero.
 *
 * **Fire-and-forget, and every failure is swallowed** — the same contract as
 * the haptics module. A device on silent, without an audio route, or mid-call
 * must never turn a completed hold into an error: the set is already on disk by
 * the time any of this runs.
 *
 * No `setAudioModeAsync` call. Its defaults are already what an alert wants —
 * `playsInSilentMode` is true, and `interruptionMode` is `mixWithOthers`, so a
 * beep does not stop whatever you are listening to while you train.
 *
 * The files are generated by `scripts/tones.py`, which holds the pitches and
 * the reasoning about them. Regenerate rather than edit.
 */

const sources = {
  tick: require('../assets/tone-tick.wav'),
  stop: require('../assets/tone-stop.wav'),
  go: require('../assets/tone-go.wav'),
};

type Tone = keyof typeof sources;

/**
 * Built once each, lazily, and kept. A player per beep would allocate a decoder
 * for every set and make the first sound lag behind the moment it is reporting.
 */
const players = new Map<Tone, AudioPlayer | null>();

function ensurePlayer(tone: Tone): AudioPlayer | null {
  const existing = players.get(tone);

  if (existing !== undefined) {
    return existing;
  }

  let player: AudioPlayer | null;

  try {
    player = createAudioPlayer(sources[tone]);
  } catch {
    player = null;
  }

  // Cached even when null, so a device that cannot build a player does not
  // retry the failure on every set.
  players.set(tone, player);

  return player;
}

/**
 * Rewinds first: after the first set the player sits at the end of the clip,
 * and `play` from there is silence. The seek is asynchronous, so playback is
 * chained onto it rather than raced against it.
 */
function play(tone: Tone): void {
  const player = ensurePlayer(tone);

  if (!player) {
    return;
  }

  player
    .seekTo(0)
    .then(() => player.play())
    .catch(() => {
      // Deliberately silent. See the contract above.
    });
}

/**
 * One second of the countdown has gone (§8.2). Fired at three and at two, and
 * deliberately short: it is a count, not an instruction, and two of them are
 * about to be followed by something that sounds nothing like them.
 */
export function beepCountdown(): void {
  play('tick');
}

/**
 * The hold is over. Stop.
 *
 * Fired on the last second rather than at zero, so it finishes as the figure
 * reaches zero and the set is written into silence.
 */
export function beepHoldOver(): void {
  play('stop');
}

/**
 * Rest is over and the next set is starting (§8.2). Go.
 *
 * Fired on the last second, for the same reason as the hold ending and one of
 * its own: it is the instruction to move, and a tone that began once the next
 * hold was already running would be announcing time you had lost.
 */
export function beepRestOver(): void {
  play('go');
}
